services:
  web:
    build:
      context: /mnt/user/appdata/oposicionesweb
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /mnt/user/cursos:/cursos
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped
    command: python app.py

  db:
    image: postgres:15
    volumes:
      - /mnt/user/appdata/oposicionesweb/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=oposicionesdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d oposicionesdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped